default: &default
  adapter: postgresql
  timeout: 5000
  pool: 5
  encoding: unicode 

development:
  <<: *default
  database: postgres
  username: habitatx
  password: your_password
  host: localhost

test:
  <<: *default
  database: postgres
  username: habitatx
  password: your_password
  host: localhost

production:
  <<: *default
  database: postgres
  username: habitatx
  password: your_password
  host: localhost
